USER_CREATE_API =  "/create/"
LOGIN_API = "/login/"
GET_ALL_USERS_LIST_WITH_PAGINATION = "/get_all_users"
GET_USER_BY_ID_API = "/get_user_by_id/"
UPDATE_USER_DETAILS = "/update_user_details/"
UPDATE_USER_PASSWORD_DETAILS = "/update_user_password_details/"
DELETE_USER_API = "/delete_user/"

ROLE_CREATE_API = "/create/"
GET_ALL_ROLE_LIST = "/get_all_role/"
GET_ROLE_BY_ID = "/get_role_by_id/"
UPDATE_ROLE_BY_ID = "/update_role/"
DELETE_ROLE_BY_ID = "/delete_role/"

TAG_CREATE_API = "/create/"
GET_ALL_TAG_LIST = "/get_all_tag/"
GET_TAG_BY_ID = "/get_tag_by_id/"
UPDATE_TAG_BY_ID = "/update_tag/"
DELETE_TAG_BY_ID = "/delete_tag/"

